version: "3.1"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - spring-ms

  espark-mysql:
    container_name: espark-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=espark
      - MYSQL_USER=espark-root
      - MYSQL_PASSWORD=espark-root
    ports:
      - 3306:3306
    volumes:
      - /data/espark-mysql
    depends_on:
      - rabbitmq
    networks:
      - spring-ms

  springboot-streams-rabbit-docker:
    image: springboot-streams-rabbit-docker
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    volumes:
      - /data/springboot-streams-rabbit-docker
    ports:
      - 9090:9090
    links:
      - rabbitmq
      - espark-mysql
    depends_on:
      - rabbitmq
      - espark-mysql
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_GROUP=espark-group
      - RABBITMQ_DESTINATION=espark
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - DATABASE_HOST=espark-mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=espark
      - DATABASE_USER=espark-root
      - DATABASE_PASSWORD=espark-root
    networks:
      - spring-ms

networks:
  spring-ms: