version: "3"
services:
  nginx:
   image: nginx
   restart: always
   ports:
   - 80:80
   - 443:443
   networks:
     - spring-ms
   volumes:
   - ./nginx/conf.d /etc/nginx/conf.d

  springboot-app:
    image: springboot-app
    restart: always
    build:
      context: ./springboot-app
      dockerfile: Dockerfile
    volumes:
      - ./data/springboot-app
    ports:
      - "9090:9090"
    depends_on:
      - nginx
    networks:
      - spring-ms
networks:
  spring-ms: