version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"

  spring-boot-rest-api-app:
    restart: always
    image: spring-boot-rest-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    environment:
      - SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq:5672
    links:
      - rabbitmq
    volumes:
      - /data/spring-boot-app
    depends_on:
      - rabbitmq



