version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS="-Xmx2048m -Xms2048m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    volumes:
        - esdata1:/usr/share/elasticsearch/data
    ports:
        - "9200:9200"
        - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - spring-ms

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - spring-ms

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - spring-ms

  springboot-elk-docker:
    image: springboot-elk-docker
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - "18080:8080"
      - "18787:8787"
      - "8080:8080"
    links:
      - elasticsearch
      - kibana
      - logstash
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    networks:
      - spring-ms

volumes:
  esdata1:
    driver: local

networks:
  spring-ms: