version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
        - esdata1:/usr/share/elasticsearch/data
    ports:
        - "9200:9200"
        - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - spring-ms

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - spring-ms

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - spring-ms

  springboot-elk-docker:
    image: springboot-elk-docker
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8080:8080"
    links:
      - elasticsearch
      - kibana
      - logstash
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    networks:
      - spring-ms

volumes:
  esdata1:
    driver: local

networks:
  spring-ms:
