
server:
  port: 9090

spring:
  application:
    name: springboot-cassandra
  profiles: default
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      keyspace-name: espark
      schema-action: create_if_not_exists
      entity-base-package: com.espark.adarsh.entity
      local-datacenter: Cassandra

---
#
#spring:
#  application:
#    name: springboot-cassandra
#  profiles: docker
#  data:
#    cassandra:
#      user-name: ${CASSANDRA_USERNAME}
#      password: ${CASSANDRA_PWD}
#      keyspace-name: ${CASSANDRA_KEYSPACE}
#      port: ${CASSANDRA_PORT}
#      contact-points: ${CASSANDRA_HOST}
#      schema-action: create_if_not_exists
#      entity-base-package: com.espark.adarsh.entity
#      local-datacenter: ${CASSANDRA_DC}