spring:
  application:
    name: springboot-cassandra
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      keyspace-name: espark
      schema-action: create_if_not_exists
      entity-base-package: com.espark.adarsh.entity
      local-datacenter: Cassandra
      username: cassandra
      password: cassandra

---

spring:
  application:
    name: springboot-cassandra
  profiles:
    - docker
    - kubernates
  data:
    cassandra:
      port: ${CASSANDRA_PORT}
      contact-points: ${CASSANDRA_HOST}
      keyspace-name: ${CASSANDRA_KEYSPACE}
      schema-action: create_if_not_exists
      entity-base-package: com.espark.adarsh.entity
      local-datacenter: ${CASSANDRA_DC}
      username:  ${CASSANDRA_USERNAME}
      password: ${CASSANDRA_PWD}