version: "3.2"
services:
  espark-postgres:
    image: postgres:9.5
    container_name: espark-postgres
    volumes:
        - espark-postgres:/var/lib/postgresql/data
    environment:
        - DB_DRIVER=org.postgresql.Driver
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
        - POSTGRES_DB=espark
        - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
        - 5432:5432

  springboot-jpa-postgrace-docker:
    image: springboot-jpa-postgrace-docker
    depends_on:
      - espark-postgres
    links:
      - espark-postgres
    ports:
      - 9090:9090
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=espark
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    espark-postgres: {}

