
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    com.espark.adarsh: DEBUG

server:
  port: 8080

spring:
  application:
    name: springboot-elg-docker
  logstash:
    url: localhost:5000
    host: localhost
    port: 5000
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10  #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


---


logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    com.espark.adarsh: DEBUG

server:
  port: 8080

spring:
  application:
    name: springboot-elg-docker
  profiles:
    - docker
  logstash:
    url: logstash:5000
    host: logstash
    port: 5000
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10  #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true