server:
  port: 9090

spring:
  application:
    name: docker-hazelcast
  datasource:
    url: jdbc:mysql://espark-mysql:3306/espark?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          hazelcast:
#            instance_name: cache-1
            use_native_client: true
            native_client_address: 192.168.99.100:5701
            native_client_group: dev
            native_client_password: dev-pass
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

logging:
  level:
    com.hazelcast: DEBUG
    org.hibernate: DEBUG
