version: '3.7'

services:

  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:latest
    ports:
      - 9042:9042
    restart: always
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_DC=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CQL_PORT_NUMBER=9042
    networks:
      - app-tier

  springboot-cassandra:
    container_name: springboot-cassandra
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - 8080:8080
    links:
      - cassandra
    depends_on:
      - cassandra
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CASSANDRA_KEYSPACE=espark
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_DC=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PWD=cassandra
    networks:
      - app-tier

networks:
  app-tier: